version: '3'
services:
  vc_web_app: 
    build: .
    ports:
      - 5009:5009
    image: vc_web_app_img
    container_name: vc_web_app_ctr
    working_dir: /src
    tty: true
    volumes:
      - ./src:/src
    
    # gpuを用いる場合は以下のコメントを外す
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
    # environment:
    #   - NVIDIA_VISIBLE_DEVICES=all
    #   - NVIDIA_DRIVER_CAPAVILITIES=all
  
  db:
    build: ./docker-mysql/
    volumes:
      # - ./DB:/docker-entrypoint-initdb.d
      - ./docker-mysql/DB:/var/lib/mysql
    ports:
      - 5010:5010
    image: mysql:8.0.36-debian
    container_name: db
    # working_dir: /src
    tty: true
    environment:
      - MYSQL_DATABASE=app_db
      - MYSQL_USER=username
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root_password