[tool.poetry]
name = "sample"
version = "0.1.0"
description = ""
authors = ["Halu <tanaka0507official@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry", "poetry-core"]
build-backend = "poetry.core.masonry.api"
